data:
  name: sdo-benchmark
  validation_size: 0.1
  channel: [magnetogram]
  size: 256
  targets:
    classes:
      - Quiet: "< 1e-6"
      - ">=C": ">= 1e-6"
  time_steps: [0, 1, 2, 3 ]
  path: /srv/beegfs/scratch/users/s/shtyk1/SDOBenchmark-data-full
type: one
is_train: false
seed: 42
split_type: bal



model:
  backbone: resnet18
  learning_rate: 0.005
  activation: relu6
  pooling: 2
  dropout: 0.2
  n_hidden: 16
  lr_scheduler: true

trainer:
  epochs: 300
  patience: 20
  batch_size: 128

name: Baseline binary classification model
training_type: train # train, finetune, ssl
tune_lr: false
tracking: false
path: /srv/beegfs/scratch/users/s/shtyk1/resnet_magn/model6


optimizer_type: SGD
type_class: 1

system:
  gpus: 1
  workers: 8